version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "123455678"
      MYSQL_DATABASE: "dockerDB"
    ports:
      - "3307:3306"
    volumes:
      - ./databases:/var/lib/mysql
    

 
