version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "123455678"
      MYSQL_DATABASE: "dockerDB"
    ports:
      - "3306:3306"
    volumes:
      - /home/gustavosouza/Workspace/TRYBE/Docker/volumes/mysql:/var/lib/mysql
    

 
